# --------------------------------------------------------------------------- #
# Developer: Andrew Kirfman                                                   #
# Project: CSCE-313 Episode #4                                                #
#                                                                             #
# File: ./Makefile                                                            #
# --------------------------------------------------------------------------- #


CC=g++
STD=-std=c++11
CFLAGS=-O3 -Wall -g

all: mp4_test.cpp
	$(CC) $(STD) $(CFLAGS) mp4_test.cpp -o mp4_test


clean:
	rm -rf proctest
