# --------------------------------------------------------------------------- #
# Developer: Andrew Kirfman                                                   #
# Project: CSCE-313 Episode #4                                                #
#                                                                             #
# File: ./Makefile                                                            #
# --------------------------------------------------------------------------- #


CC=g++
STD=-std=c++11
CFLAGS=-O3 -Wall -g

all: examples.cpp
	$(CC) $(STD) $(CFLAGS) examples.cpp -o examples


clean:
	rm -rf examples
