# --------------------------------------------------------------------------- #
# Developer: Andrew Kirfman                                                   #
# Project: CSCE-313 Machine Problem #6                                        #
#                                                                             #
# File: ./MP6/Makefile                                                        #
# --------------------------------------------------------------------------- #


CC=g++
STD=-std=c++11
CFLAGS=-O3 -Wall -g


all: main.cpp
	$(CC) $(CFLAGS) $(STD) main.cpp -o scheduler

clean:
	rm -rf scheduler
